version: '3'
services:
  mongo:
    image: mongo:${VER_MONGO}
    deploy:
      placement:
        constraints:
          - node.labels.reliability == high
  rabbit:
    image: rabbitmq:latest

  search_engine_ui:
    image: vsb2007/search_engine_ui:latest
    ports:
      - 8000:8000/tcp
    restart: always

  search_engine_crawler:
    image: vsb2007/search_engine_crawler:latest
    ports:
      - 8001:8000/tcp
    restart: always
